add_test([=[ReaderTest.CanBeCreated]=]  /home/runner/work/NiForge/NiForge/_codeql_build_dir/bin/NiForgeTests [==[--gtest_filter=ReaderTest.CanBeCreated]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReaderTest.CanBeCreated]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/NiForge/NiForge/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReadFileTest.CanReadFile]=]  /home/runner/work/NiForge/NiForge/_codeql_build_dir/bin/NiForgeTests [==[--gtest_filter=ReadFileTest.CanReadFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReadFileTest.CanReadFile]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/NiForge/NiForge/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParseFile.CanParseFile]=]  /home/runner/work/NiForge/NiForge/_codeql_build_dir/bin/NiForgeTests [==[--gtest_filter=ParseFile.CanParseFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParseFile.CanParseFile]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/NiForge/NiForge/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParseFile.CanParseFile2]=]  /home/runner/work/NiForge/NiForge/_codeql_build_dir/bin/NiForgeTests [==[--gtest_filter=ParseFile.CanParseFile2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParseFile.CanParseFile2]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/NiForge/NiForge/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ParseFile.CanParseFile3]=]  /home/runner/work/NiForge/NiForge/_codeql_build_dir/bin/NiForgeTests [==[--gtest_filter=ParseFile.CanParseFile3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ParseFile.CanParseFile3]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/NiForge/NiForge/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  NiForgeTests_TESTS ReaderTest.CanBeCreated ReadFileTest.CanReadFile ParseFile.CanParseFile ParseFile.CanParseFile2 ParseFile.CanParseFile3)
